# Site settings
title: copoCAT
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lee Gyuwon
user_description:![img1](https://user-images.githubusercontent.com/115914965/196036937-f7d924a0-77f1-4a99-83af-59df9f129812.JPG)
user_title: DGU Computer Science & Engineering
email: leeguewon2001@gmail.com
instagram_username: def_gyuwon
facebook_username: none
linkedin_username: leeguewon
github_username:  copoDOG

exclude: ['package.json', 'src' , 'node_modules']
