# Site settings
title: copoCAT
description: Lee Gyuwon | DGU WISE Computer Engineering
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lee Gyuwon
user_description:
user_title: DGU Computer Science & Engineering
email: leeguewon2001@gmail.com
instagram_username: def_gyuwon
facebook_username: none
linkedin_username: leeguewon
github_username:  copoDOG

exclude: ['package.json', 'src' , 'node_modules']
